### ISSUE TITLE
support python 3.6 on pip

### ISSUE THREAD

**Issue by mateuszzz88** [chagui/ninjavis#13]
I wanted to try ninjavis with least effort so I tried `pip3 install --user ninjavis`. 
All I got was 
```
$  pip3 install --user ninjavis
Collecting ninjavis
  Could not find a version that satisfies the requirement ninjavis (from versions: )
No matching distribution found for ninjavis
```
I have Python 3.6.9 on Ubuntu 18.04.4 LTS.

**Comment by chagui** [comment]
Hey @mateuszzz88,
Thanks for having a look into ninjavis!
In order to support python 3.6 we would have to drop data-classes. Before considering it, would it be an option for you to use docker?
Note: I just realized the dockerfile needs to be updated, which I'll do now :wink:

**Comment by mateuszzz88** [comment]
I guess I will have to try it out at home, but for work neither docker nor python upgrade are currently possible. 

In any case: currently I use https://github.com/nico/ninjatracing with https://github.com/catapult-project/catapult for trace2html, but the latter is very heavy. I wanted do see if ninjavis has enough features at smaller size.

**Comment by chagui** [comment]
Funny thing is that I wrote ninjavis for the exact same reason :smile: 
Let me look into a dependency-free version compatible with 3.6 then. Depending on how that look I'll merge it.

Edit: It didn't look bad so I will merge it in main.

**Comment by chagui** [comment]
#15 will be release in 0.2.0. Please note that travis may take sometimes to process the job. You can track the version on [pypi](https://pypi.org/project/ninjavis).
